<?php
/**
 * RecordingsFormatApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RecordingsFormatApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecordingsFormatApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancel
     *
     * Stop a live recording and discard it..
     *
     */
    public function testCancel()
    {
    }

    /**
     * Test case for copyStored
     *
     * Copy a stored recording..
     *
     */
    public function testCopyStored()
    {
    }

    /**
     * Test case for deleteStored
     *
     * Delete a stored recording..
     *
     */
    public function testDeleteStored()
    {
    }

    /**
     * Test case for getLive
     *
     * List live recordings..
     *
     */
    public function testGetLive()
    {
    }

    /**
     * Test case for getStored
     *
     * Get a stored recording's details..
     *
     */
    public function testGetStored()
    {
    }

    /**
     * Test case for getStoredFile
     *
     * Get the file associated with the stored recording..
     *
     */
    public function testGetStoredFile()
    {
    }

    /**
     * Test case for listStored
     *
     * List recordings that are complete..
     *
     */
    public function testListStored()
    {
    }

    /**
     * Test case for mute
     *
     * Mute a live recording..
     *
     */
    public function testMute()
    {
    }

    /**
     * Test case for pause
     *
     * Pause a live recording..
     *
     */
    public function testPause()
    {
    }

    /**
     * Test case for stop
     *
     * Stop a live recording and store it..
     *
     */
    public function testStop()
    {
    }

    /**
     * Test case for unmute
     *
     * Unmute a live recording..
     *
     */
    public function testUnmute()
    {
    }

    /**
     * Test case for unpause
     *
     * Unpause a live recording..
     *
     */
    public function testUnpause()
    {
    }
}
