<?php
/**
 * Dial
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Dial Class Doc Comment
 *
 * @category Class
 * @description Dialing state has changed.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Dial implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Dial';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'caller' => '\Swagger\Client\Model\Channel',
        'peer' => '\Swagger\Client\Model\Channel',
        'forward' => 'string',
        'forwarded' => '\Swagger\Client\Model\Channel',
        'dialstring' => 'string',
        'dialstatus' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'caller' => null,
        'peer' => null,
        'forward' => null,
        'forwarded' => null,
        'dialstring' => null,
        'dialstatus' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'caller' => 'caller',
        'peer' => 'peer',
        'forward' => 'forward',
        'forwarded' => 'forwarded',
        'dialstring' => 'dialstring',
        'dialstatus' => 'dialstatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'caller' => 'setCaller',
        'peer' => 'setPeer',
        'forward' => 'setForward',
        'forwarded' => 'setForwarded',
        'dialstring' => 'setDialstring',
        'dialstatus' => 'setDialstatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'caller' => 'getCaller',
        'peer' => 'getPeer',
        'forward' => 'getForward',
        'forwarded' => 'getForwarded',
        'dialstring' => 'getDialstring',
        'dialstatus' => 'getDialstatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['caller'] = isset($data['caller']) ? $data['caller'] : null;
        $this->container['peer'] = isset($data['peer']) ? $data['peer'] : null;
        $this->container['forward'] = isset($data['forward']) ? $data['forward'] : null;
        $this->container['forwarded'] = isset($data['forwarded']) ? $data['forwarded'] : null;
        $this->container['dialstring'] = isset($data['dialstring']) ? $data['dialstring'] : null;
        $this->container['dialstatus'] = isset($data['dialstatus']) ? $data['dialstatus'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets caller
     *
     * @return \Swagger\Client\Model\Channel
     */
    public function getCaller()
    {
        return $this->container['caller'];
    }

    /**
     * Sets caller
     *
     * @param \Swagger\Client\Model\Channel $caller The calling channel.
     *
     * @return $this
     */
    public function setCaller($caller)
    {
        $this->container['caller'] = $caller;

        return $this;
    }

    /**
     * Gets peer
     *
     * @return \Swagger\Client\Model\Channel
     */
    public function getPeer()
    {
        return $this->container['peer'];
    }

    /**
     * Sets peer
     *
     * @param \Swagger\Client\Model\Channel $peer The dialed channel.
     *
     * @return $this
     */
    public function setPeer($peer)
    {
        $this->container['peer'] = $peer;

        return $this;
    }

    /**
     * Gets forward
     *
     * @return string
     */
    public function getForward()
    {
        return $this->container['forward'];
    }

    /**
     * Sets forward
     *
     * @param string $forward Forwarding target requested by the original dialed channel.
     *
     * @return $this
     */
    public function setForward($forward)
    {
        $this->container['forward'] = $forward;

        return $this;
    }

    /**
     * Gets forwarded
     *
     * @return \Swagger\Client\Model\Channel
     */
    public function getForwarded()
    {
        return $this->container['forwarded'];
    }

    /**
     * Sets forwarded
     *
     * @param \Swagger\Client\Model\Channel $forwarded Channel that the caller has been forwarded to.
     *
     * @return $this
     */
    public function setForwarded($forwarded)
    {
        $this->container['forwarded'] = $forwarded;

        return $this;
    }

    /**
     * Gets dialstring
     *
     * @return string
     */
    public function getDialstring()
    {
        return $this->container['dialstring'];
    }

    /**
     * Sets dialstring
     *
     * @param string $dialstring The dial string for calling the peer channel.
     *
     * @return $this
     */
    public function setDialstring($dialstring)
    {
        $this->container['dialstring'] = $dialstring;

        return $this;
    }

    /**
     * Gets dialstatus
     *
     * @return string
     */
    public function getDialstatus()
    {
        return $this->container['dialstatus'];
    }

    /**
     * Sets dialstatus
     *
     * @param string $dialstatus Current status of the dialing attempt to the peer.
     *
     * @return $this
     */
    public function setDialstatus($dialstatus)
    {
        $this->container['dialstatus'] = $dialstatus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


