<?php
/**
 * RTPstatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RTPstatTest Class Doc Comment
 *
 * @category    Class
 * @description A statistics of a RTP.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RTPstatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RTPstat"
     */
    public function testRTPstat()
    {
    }

    /**
     * Test attribute "txcount"
     */
    public function testPropertyTxcount()
    {
    }

    /**
     * Test attribute "rxcount"
     */
    public function testPropertyRxcount()
    {
    }

    /**
     * Test attribute "txjitter"
     */
    public function testPropertyTxjitter()
    {
    }

    /**
     * Test attribute "rxjitter"
     */
    public function testPropertyRxjitter()
    {
    }

    /**
     * Test attribute "remote_maxjitter"
     */
    public function testPropertyRemoteMaxjitter()
    {
    }

    /**
     * Test attribute "remote_minjitter"
     */
    public function testPropertyRemoteMinjitter()
    {
    }

    /**
     * Test attribute "remote_normdevjitter"
     */
    public function testPropertyRemoteNormdevjitter()
    {
    }

    /**
     * Test attribute "remote_stdevjitter"
     */
    public function testPropertyRemoteStdevjitter()
    {
    }

    /**
     * Test attribute "local_maxjitter"
     */
    public function testPropertyLocalMaxjitter()
    {
    }

    /**
     * Test attribute "local_minjitter"
     */
    public function testPropertyLocalMinjitter()
    {
    }

    /**
     * Test attribute "local_normdevjitter"
     */
    public function testPropertyLocalNormdevjitter()
    {
    }

    /**
     * Test attribute "local_stdevjitter"
     */
    public function testPropertyLocalStdevjitter()
    {
    }

    /**
     * Test attribute "txploss"
     */
    public function testPropertyTxploss()
    {
    }

    /**
     * Test attribute "rxploss"
     */
    public function testPropertyRxploss()
    {
    }

    /**
     * Test attribute "remote_maxrxploss"
     */
    public function testPropertyRemoteMaxrxploss()
    {
    }

    /**
     * Test attribute "remote_minrxploss"
     */
    public function testPropertyRemoteMinrxploss()
    {
    }

    /**
     * Test attribute "remote_normdevrxploss"
     */
    public function testPropertyRemoteNormdevrxploss()
    {
    }

    /**
     * Test attribute "remote_stdevrxploss"
     */
    public function testPropertyRemoteStdevrxploss()
    {
    }

    /**
     * Test attribute "local_maxrxploss"
     */
    public function testPropertyLocalMaxrxploss()
    {
    }

    /**
     * Test attribute "local_minrxploss"
     */
    public function testPropertyLocalMinrxploss()
    {
    }

    /**
     * Test attribute "local_normdevrxploss"
     */
    public function testPropertyLocalNormdevrxploss()
    {
    }

    /**
     * Test attribute "local_stdevrxploss"
     */
    public function testPropertyLocalStdevrxploss()
    {
    }

    /**
     * Test attribute "rtt"
     */
    public function testPropertyRtt()
    {
    }

    /**
     * Test attribute "maxrtt"
     */
    public function testPropertyMaxrtt()
    {
    }

    /**
     * Test attribute "minrtt"
     */
    public function testPropertyMinrtt()
    {
    }

    /**
     * Test attribute "normdevrtt"
     */
    public function testPropertyNormdevrtt()
    {
    }

    /**
     * Test attribute "stdevrtt"
     */
    public function testPropertyStdevrtt()
    {
    }

    /**
     * Test attribute "local_ssrc"
     */
    public function testPropertyLocalSsrc()
    {
    }

    /**
     * Test attribute "remote_ssrc"
     */
    public function testPropertyRemoteSsrc()
    {
    }

    /**
     * Test attribute "txoctetcount"
     */
    public function testPropertyTxoctetcount()
    {
    }

    /**
     * Test attribute "rxoctetcount"
     */
    public function testPropertyRxoctetcount()
    {
    }

    /**
     * Test attribute "channel_uniqueid"
     */
    public function testPropertyChannelUniqueid()
    {
    }
}
