<?php
/**
 * ApplicationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationTest Class Doc Comment
 *
 * @category    Class
 * @description Details of a Stasis application
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Application"
     */
    public function testApplication()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "channel_ids"
     */
    public function testPropertyChannelIds()
    {
    }

    /**
     * Test attribute "bridge_ids"
     */
    public function testPropertyBridgeIds()
    {
    }

    /**
     * Test attribute "endpoint_ids"
     */
    public function testPropertyEndpointIds()
    {
    }

    /**
     * Test attribute "device_names"
     */
    public function testPropertyDeviceNames()
    {
    }

    /**
     * Test attribute "events_allowed"
     */
    public function testPropertyEventsAllowed()
    {
    }

    /**
     * Test attribute "events_disallowed"
     */
    public function testPropertyEventsDisallowed()
    {
    }
}
