<?php
/**
 * BridgeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BridgeTest Class Doc Comment
 *
 * @category    Class
 * @description The merging of media from one or more channels.  Everyone on the bridge receives the same audio.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BridgeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Bridge"
     */
    public function testBridge()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "technology"
     */
    public function testPropertyTechnology()
    {
    }

    /**
     * Test attribute "bridge_type"
     */
    public function testPropertyBridgeType()
    {
    }

    /**
     * Test attribute "bridge_class"
     */
    public function testPropertyBridgeClass()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "video_mode"
     */
    public function testPropertyVideoMode()
    {
    }

    /**
     * Test attribute "video_source_id"
     */
    public function testPropertyVideoSourceId()
    {
    }

    /**
     * Test attribute "creationtime"
     */
    public function testPropertyCreationtime()
    {
    }
}
