<?php
/**
 * BridgeAttendedTransferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BridgeAttendedTransferTest Class Doc Comment
 *
 * @category    Class
 * @description Notification that an attended transfer has occurred.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BridgeAttendedTransferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BridgeAttendedTransfer"
     */
    public function testBridgeAttendedTransfer()
    {
    }

    /**
     * Test attribute "transferer_first_leg"
     */
    public function testPropertyTransfererFirstLeg()
    {
    }

    /**
     * Test attribute "transferer_second_leg"
     */
    public function testPropertyTransfererSecondLeg()
    {
    }

    /**
     * Test attribute "replace_channel"
     */
    public function testPropertyReplaceChannel()
    {
    }

    /**
     * Test attribute "transferee"
     */
    public function testPropertyTransferee()
    {
    }

    /**
     * Test attribute "transfer_target"
     */
    public function testPropertyTransferTarget()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }

    /**
     * Test attribute "is_external"
     */
    public function testPropertyIsExternal()
    {
    }

    /**
     * Test attribute "transferer_first_leg_bridge"
     */
    public function testPropertyTransfererFirstLegBridge()
    {
    }

    /**
     * Test attribute "transferer_second_leg_bridge"
     */
    public function testPropertyTransfererSecondLegBridge()
    {
    }

    /**
     * Test attribute "destination_type"
     */
    public function testPropertyDestinationType()
    {
    }

    /**
     * Test attribute "destination_bridge"
     */
    public function testPropertyDestinationBridge()
    {
    }

    /**
     * Test attribute "destination_application"
     */
    public function testPropertyDestinationApplication()
    {
    }

    /**
     * Test attribute "destination_link_first_leg"
     */
    public function testPropertyDestinationLinkFirstLeg()
    {
    }

    /**
     * Test attribute "destination_link_second_leg"
     */
    public function testPropertyDestinationLinkSecondLeg()
    {
    }

    /**
     * Test attribute "destination_threeway_channel"
     */
    public function testPropertyDestinationThreewayChannel()
    {
    }

    /**
     * Test attribute "destination_threeway_bridge"
     */
    public function testPropertyDestinationThreewayBridge()
    {
    }
}
