<?php
/**
 * DialTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DialTest Class Doc Comment
 *
 * @category    Class
 * @description Dialing state has changed.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DialTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Dial"
     */
    public function testDial()
    {
    }

    /**
     * Test attribute "caller"
     */
    public function testPropertyCaller()
    {
    }

    /**
     * Test attribute "peer"
     */
    public function testPropertyPeer()
    {
    }

    /**
     * Test attribute "forward"
     */
    public function testPropertyForward()
    {
    }

    /**
     * Test attribute "forwarded"
     */
    public function testPropertyForwarded()
    {
    }

    /**
     * Test attribute "dialstring"
     */
    public function testPropertyDialstring()
    {
    }

    /**
     * Test attribute "dialstatus"
     */
    public function testPropertyDialstatus()
    {
    }
}
