<?php
/**
 * ChannelsFormatApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ChannelsFormatApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChannelsFormatApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for answer
     *
     * Answer a channel..
     *
     */
    public function testAnswer()
    {
    }

    /**
     * Test case for callList
     *
     * List all active channels in Asterisk..
     *
     */
    public function testCallList()
    {
    }

    /**
     * Test case for continueInDialplan
     *
     * Exit application; continue execution in the dialplan..
     *
     */
    public function testContinueInDialplan()
    {
    }

    /**
     * Test case for create
     *
     * Create channel..
     *
     */
    public function testCreate()
    {
    }

    /**
     * Test case for dial
     *
     * Dial a created channel..
     *
     */
    public function testDial()
    {
    }

    /**
     * Test case for externalMedia
     *
     * Start an External Media session..
     *
     */
    public function testExternalMedia()
    {
    }

    /**
     * Test case for get
     *
     * Channel details..
     *
     */
    public function testGet()
    {
    }

    /**
     * Test case for getChannelVar
     *
     * Get the value of a channel variable or function..
     *
     */
    public function testGetChannelVar()
    {
    }

    /**
     * Test case for hangup
     *
     * Delete (i.e. hangup) a channel..
     *
     */
    public function testHangup()
    {
    }

    /**
     * Test case for hold
     *
     * Hold a channel..
     *
     */
    public function testHold()
    {
    }

    /**
     * Test case for move
     *
     * Move the channel from one Stasis application to another..
     *
     */
    public function testMove()
    {
    }

    /**
     * Test case for mute
     *
     * Mute a channel..
     *
     */
    public function testMute()
    {
    }

    /**
     * Test case for originate
     *
     * Create a new channel (originate)..
     *
     */
    public function testOriginate()
    {
    }

    /**
     * Test case for originateWithId
     *
     * Create a new channel (originate with id)..
     *
     */
    public function testOriginateWithId()
    {
    }

    /**
     * Test case for play
     *
     * Start playback of media..
     *
     */
    public function testPlay()
    {
    }

    /**
     * Test case for playWithId
     *
     * Start playback of media and specify the playbackId..
     *
     */
    public function testPlayWithId()
    {
    }

    /**
     * Test case for record
     *
     * Start a recording..
     *
     */
    public function testRecord()
    {
    }

    /**
     * Test case for redirect
     *
     * Redirect the channel to a different location..
     *
     */
    public function testRedirect()
    {
    }

    /**
     * Test case for ring
     *
     * Indicate ringing to a channel..
     *
     */
    public function testRing()
    {
    }

    /**
     * Test case for ringStop
     *
     * Stop ringing indication on a channel if locally generated..
     *
     */
    public function testRingStop()
    {
    }

    /**
     * Test case for rtpstatistics
     *
     * RTP stats on a channel..
     *
     */
    public function testRtpstatistics()
    {
    }

    /**
     * Test case for sendDTMF
     *
     * Send provided DTMF to a given channel..
     *
     */
    public function testSendDTMF()
    {
    }

    /**
     * Test case for setChannelVar
     *
     * Set the value of a channel variable or function..
     *
     */
    public function testSetChannelVar()
    {
    }

    /**
     * Test case for snoopChannel
     *
     * Start snooping..
     *
     */
    public function testSnoopChannel()
    {
    }

    /**
     * Test case for snoopChannelWithId
     *
     * Start snooping..
     *
     */
    public function testSnoopChannelWithId()
    {
    }

    /**
     * Test case for startMoh
     *
     * Play music on hold to a channel..
     *
     */
    public function testStartMoh()
    {
    }

    /**
     * Test case for startSilence
     *
     * Play silence to a channel..
     *
     */
    public function testStartSilence()
    {
    }

    /**
     * Test case for stopMoh
     *
     * Stop playing music on hold to a channel..
     *
     */
    public function testStopMoh()
    {
    }

    /**
     * Test case for stopSilence
     *
     * Stop playing silence to a channel..
     *
     */
    public function testStopSilence()
    {
    }

    /**
     * Test case for unhold
     *
     * Remove a channel from hold..
     *
     */
    public function testUnhold()
    {
    }

    /**
     * Test case for unmute
     *
     * Unmute a channel..
     *
     */
    public function testUnmute()
    {
    }
}
